[package]
name = "chearmyp_parser"
version = "0.6.0-dev"
authors = ["Kenneth Trecy Tobias <33564322+KennethTrecy@users.noreply.github.com>"]
edition = "2018"

[dependencies]
chearmyp_lexer = { git = "http://chearmyp.local/chearmyp_lexer", tag = "v0.5.0" }
